name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull Latest Code and Restart Application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd /var/www/vuejs
            git pull origin master  # Remplace par "main" si nécessaire
            npm install
            npm run build
            sudo systemctl restart nginx  # Redémarrer Nginx si nécessaire
